`timescale 1ns / 1ps
//==============================================================================
// edge_encoder_layer_2.v  --  Auto-generated by gen_encoder_layers.py
//
// Layer 2: 32 inputs -> 32 neurons -> rms norm -> 32 x 8-bit Q4.4 outputs
//==============================================================================
module edge_encoder_layer_2 #(
    parameter LAYER_NO        = 2,
    parameter NUM_NEURONS     = 32,
    parameter NUM_FEATURES    = 32,
    parameter DATA_BITS       = 8,
    parameter WEIGHT_BITS     = 8,
    parameter BIAS_BITS       = 8,
    // RMS norm
    parameter LN_DATA_BITS      = 24,
    parameter LN_DATA_FRAC_BITS = 10,
    parameter LN_SCALE_BITS     = 8,
    parameter LN_FRAC_BITS      = 6,
    parameter LN_INV_SQRT_BITS  = 16,
    parameter LN_INV_SQRT_FRAC  = 11,
    parameter LN_VAR_BITS       = 45,
    parameter LN_LUT_BITS       = 5,
    parameter LN_LUT_SIZE       = 20,
    parameter LN_EPSILON        = 1,
    parameter LN_OUT_BITS       = 8,
    parameter LN_OUT_FRAC_BITS  = 4,
    parameter USE_RMS_NORM    = 1,
    parameter GammaFile         = "ln_gamma_2.mif"
)(
    input  clk,
    input  rstn,                                                    // used as layer_held by parent
    input  activation_function,
    input  signed [NUM_FEATURES*DATA_BITS-1:0]   data_in_flat,

    output signed [NUM_NEURONS*LN_OUT_BITS-1:0]  data_out_flat,
    output valid_out,
    output done
);

    localparam NEURON_OUT_BITS = DATA_BITS + WEIGHT_BITS + 8;

    //--------------------------------------------------------------------------
    // Counter: .rstn(rstn) — parent drives rstn=layer_held, so counter runs
    // only while the layer is active.
    //--------------------------------------------------------------------------
    wire [31:0] counter;
    wire        counter_done;

    counter #(
        .END_COUNTER((NUM_FEATURES + 3) / 4)   // ceiling division — covers all features
    ) layer_counter (
        .clk               (clk),
        .rstn              (rstn),
        .counter_out       (counter),
        .counter_donestatus(counter_done)
    );

    //--------------------------------------------------------------------------
    // Computation active + done state machine.
    // done is a 1-cycle pulse after counter_done + done_delay cycles.
    // The parent (edge_encoder / node_encoder) reads valid_out (= rms_norm
    // done) as layer_done, not this done port — done() is tied open there.
    // The state machine is kept for completeness and future use.
    //--------------------------------------------------------------------------
    reg computation_active;
    reg done_reg;
    reg [2:0] done_delay_counter;

    always @(posedge clk or negedge rstn) begin
        if (!rstn) begin
            computation_active <= 0;
            done_reg           <= 0;
            done_delay_counter <= 0;
        end else begin
            if (!computation_active && !done_reg) begin
                computation_active <= 1;
                done_delay_counter <= 0;
            end else if (counter_done && computation_active && !done_reg) begin
                if (done_delay_counter < 2) begin
                    done_delay_counter <= done_delay_counter + 1;
                end else begin
                    done_reg           <= 1;
                    computation_active <= 0;
                    done_delay_counter <= 0;
                end
            end else if (done_reg) begin
                // Hold done until the parent drops layer_held after valid_out.
                computation_active <= 0;
            end
        end
    end

    assign done = done_reg;

    //--------------------------------------------------------------------------
    // Raw neuron outputs
    //--------------------------------------------------------------------------
    wire signed [NEURON_OUT_BITS-1:0] neuron_outputs [0:NUM_NEURONS-1];

    //--------------------------------------------------------------------------
    // Gamma — load from MIF, pack via generate/assign
    //--------------------------------------------------------------------------
    reg signed [LN_SCALE_BITS-1:0] gamma_arr [0:NUM_NEURONS-1];

    initial begin
        $readmemb(GammaFile, gamma_arr);
    end

    wire signed [NUM_NEURONS*LN_SCALE_BITS-1:0] ln_gamma;

    genvar gi;
    generate
        for (gi = 0; gi < NUM_NEURONS; gi = gi + 1) begin : ln_param_pack
            assign ln_gamma[gi*LN_SCALE_BITS +: LN_SCALE_BITS] = gamma_arr[gi];
        end
    endgenerate

    //--------------------------------------------------------------------------
    // ln_start: 1-cycle pulse on done_reg rising edge
    //--------------------------------------------------------------------------
    reg done_reg_r;
    reg ln_start;

    always @(posedge clk or negedge rstn) begin
        if (!rstn) begin
            done_reg_r <= 1'b0;
            ln_start   <= 1'b0;
        end else begin
            done_reg_r <= done_reg;
            ln_start   <= done_reg & ~done_reg_r;
        end
    end

    //--------------------------------------------------------------------------
    // Latch + sign-extend neuron outputs into ln_data_in on ln_start pulse
    //--------------------------------------------------------------------------
    reg signed [NUM_NEURONS*LN_DATA_BITS-1:0] ln_data_in;

    integer n;
    always @(posedge clk or negedge rstn) begin
        if (!rstn) begin
            ln_data_in <= {(NUM_NEURONS*LN_DATA_BITS){1'b0}};
        end else if (done_reg & ~done_reg_r) begin
            for (n = 0; n < NUM_NEURONS; n = n + 1) begin
                ln_data_in[n*LN_DATA_BITS +: LN_DATA_BITS] <=
                    {{(LN_DATA_BITS-NEURON_OUT_BITS){neuron_outputs[n][NEURON_OUT_BITS-1]}},
                      neuron_outputs[n]};
            end
        end
    end

    //--------------------------------------------------------------------------
    // RMS norm / bypass
    //--------------------------------------------------------------------------
    generate
        if (USE_RMS_NORM) begin : gen_rms_norm
            rms_norm #(
                .NUM_FEATURES      (NUM_NEURONS),
                .DATA_BITS         (LN_DATA_BITS),
                .DATA_FRAC_BITS    (LN_DATA_FRAC_BITS),
                .SCALE_BITS        (LN_SCALE_BITS),
                .FRAC_BITS         (LN_FRAC_BITS),
                .INV_SQRT_BITS     (LN_INV_SQRT_BITS),
                .INV_SQRT_FRAC_BITS(LN_INV_SQRT_FRAC),
                .VAR_BITS          (LN_VAR_BITS),
                .LUT_BITS          (LN_LUT_BITS),
                .LUT_SIZE          (LN_LUT_SIZE),
                .EPSILON           (LN_EPSILON),
                .OUT_BITS          (LN_OUT_BITS),
                .OUT_FRAC_BITS     (LN_OUT_FRAC_BITS)
            ) u_rms_norm (
                .clk      (clk),
                .rstn     (rstn),
                .valid_in (ln_start),
                .act_en   (activation_function),
                .data_in  (ln_data_in),
                .gamma    (ln_gamma),
                .valid_out(valid_out),
                .busy     (),
                .data_out (data_out_flat)
            );
        end else begin : gen_bypass_rms_norm
            layer_norm_relu #(
                .NUM_FEATURES      (NUM_NEURONS),
                .DATA_BITS         (LN_DATA_BITS),
                .DATA_FRAC_BITS    (LN_DATA_FRAC_BITS),
                .OUT_BITS          (LN_OUT_BITS),
                .OUT_FRAC_BITS     (LN_OUT_FRAC_BITS)
            ) u_rms_norm_bypass (
                .clk      (clk),
                .rstn     (rstn),
                .valid_in (ln_start),
                .act_en   (activation_function),
                .data_in  (ln_data_in),
                .valid_out(valid_out),
                .data_out (data_out_flat)
            );
        end
    endgenerate

    //--------------------------------------------------------------------------
    // Neuron instances
    //--------------------------------------------------------------------------
    generate

        if (NUM_NEURONS > 0) begin : neuron_0
            neuron #(
                .NEURON_WIDTH(NUM_FEATURES),
                .DATA_BITS   (DATA_BITS),
                .WEIGHT_BITS (WEIGHT_BITS),
                .BIAS_BITS   (BIAS_BITS),
                .WeightFile  ("edge_encoder_w_2_0.mif"),
                .BiasFile    ("edge_encoder_b_2_0.mif")
            ) inst (
                .clk                (clk),
                .rstn               (rstn),
                .activation_function(activation_function),
                .data_in_flat       (data_in_flat),
                .counter            (counter),
                .data_out           (neuron_outputs[0])
            );
        end

        if (NUM_NEURONS > 1) begin : neuron_1
            neuron #(
                .NEURON_WIDTH(NUM_FEATURES),
                .DATA_BITS   (DATA_BITS),
                .WEIGHT_BITS (WEIGHT_BITS),
                .BIAS_BITS   (BIAS_BITS),
                .WeightFile  ("edge_encoder_w_2_1.mif"),
                .BiasFile    ("edge_encoder_b_2_1.mif")
            ) inst (
                .clk                (clk),
                .rstn               (rstn),
                .activation_function(activation_function),
                .data_in_flat       (data_in_flat),
                .counter            (counter),
                .data_out           (neuron_outputs[1])
            );
        end

        if (NUM_NEURONS > 2) begin : neuron_2
            neuron #(
                .NEURON_WIDTH(NUM_FEATURES),
                .DATA_BITS   (DATA_BITS),
                .WEIGHT_BITS (WEIGHT_BITS),
                .BIAS_BITS   (BIAS_BITS),
                .WeightFile  ("edge_encoder_w_2_2.mif"),
                .BiasFile    ("edge_encoder_b_2_2.mif")
            ) inst (
                .clk                (clk),
                .rstn               (rstn),
                .activation_function(activation_function),
                .data_in_flat       (data_in_flat),
                .counter            (counter),
                .data_out           (neuron_outputs[2])
            );
        end

        if (NUM_NEURONS > 3) begin : neuron_3
            neuron #(
                .NEURON_WIDTH(NUM_FEATURES),
                .DATA_BITS   (DATA_BITS),
                .WEIGHT_BITS (WEIGHT_BITS),
                .BIAS_BITS   (BIAS_BITS),
                .WeightFile  ("edge_encoder_w_2_3.mif"),
                .BiasFile    ("edge_encoder_b_2_3.mif")
            ) inst (
                .clk                (clk),
                .rstn               (rstn),
                .activation_function(activation_function),
                .data_in_flat       (data_in_flat),
                .counter            (counter),
                .data_out           (neuron_outputs[3])
            );
        end

        if (NUM_NEURONS > 4) begin : neuron_4
            neuron #(
                .NEURON_WIDTH(NUM_FEATURES),
                .DATA_BITS   (DATA_BITS),
                .WEIGHT_BITS (WEIGHT_BITS),
                .BIAS_BITS   (BIAS_BITS),
                .WeightFile  ("edge_encoder_w_2_4.mif"),
                .BiasFile    ("edge_encoder_b_2_4.mif")
            ) inst (
                .clk                (clk),
                .rstn               (rstn),
                .activation_function(activation_function),
                .data_in_flat       (data_in_flat),
                .counter            (counter),
                .data_out           (neuron_outputs[4])
            );
        end

        if (NUM_NEURONS > 5) begin : neuron_5
            neuron #(
                .NEURON_WIDTH(NUM_FEATURES),
                .DATA_BITS   (DATA_BITS),
                .WEIGHT_BITS (WEIGHT_BITS),
                .BIAS_BITS   (BIAS_BITS),
                .WeightFile  ("edge_encoder_w_2_5.mif"),
                .BiasFile    ("edge_encoder_b_2_5.mif")
            ) inst (
                .clk                (clk),
                .rstn               (rstn),
                .activation_function(activation_function),
                .data_in_flat       (data_in_flat),
                .counter            (counter),
                .data_out           (neuron_outputs[5])
            );
        end

        if (NUM_NEURONS > 6) begin : neuron_6
            neuron #(
                .NEURON_WIDTH(NUM_FEATURES),
                .DATA_BITS   (DATA_BITS),
                .WEIGHT_BITS (WEIGHT_BITS),
                .BIAS_BITS   (BIAS_BITS),
                .WeightFile  ("edge_encoder_w_2_6.mif"),
                .BiasFile    ("edge_encoder_b_2_6.mif")
            ) inst (
                .clk                (clk),
                .rstn               (rstn),
                .activation_function(activation_function),
                .data_in_flat       (data_in_flat),
                .counter            (counter),
                .data_out           (neuron_outputs[6])
            );
        end

        if (NUM_NEURONS > 7) begin : neuron_7
            neuron #(
                .NEURON_WIDTH(NUM_FEATURES),
                .DATA_BITS   (DATA_BITS),
                .WEIGHT_BITS (WEIGHT_BITS),
                .BIAS_BITS   (BIAS_BITS),
                .WeightFile  ("edge_encoder_w_2_7.mif"),
                .BiasFile    ("edge_encoder_b_2_7.mif")
            ) inst (
                .clk                (clk),
                .rstn               (rstn),
                .activation_function(activation_function),
                .data_in_flat       (data_in_flat),
                .counter            (counter),
                .data_out           (neuron_outputs[7])
            );
        end

        if (NUM_NEURONS > 8) begin : neuron_8
            neuron #(
                .NEURON_WIDTH(NUM_FEATURES),
                .DATA_BITS   (DATA_BITS),
                .WEIGHT_BITS (WEIGHT_BITS),
                .BIAS_BITS   (BIAS_BITS),
                .WeightFile  ("edge_encoder_w_2_8.mif"),
                .BiasFile    ("edge_encoder_b_2_8.mif")
            ) inst (
                .clk                (clk),
                .rstn               (rstn),
                .activation_function(activation_function),
                .data_in_flat       (data_in_flat),
                .counter            (counter),
                .data_out           (neuron_outputs[8])
            );
        end

        if (NUM_NEURONS > 9) begin : neuron_9
            neuron #(
                .NEURON_WIDTH(NUM_FEATURES),
                .DATA_BITS   (DATA_BITS),
                .WEIGHT_BITS (WEIGHT_BITS),
                .BIAS_BITS   (BIAS_BITS),
                .WeightFile  ("edge_encoder_w_2_9.mif"),
                .BiasFile    ("edge_encoder_b_2_9.mif")
            ) inst (
                .clk                (clk),
                .rstn               (rstn),
                .activation_function(activation_function),
                .data_in_flat       (data_in_flat),
                .counter            (counter),
                .data_out           (neuron_outputs[9])
            );
        end

        if (NUM_NEURONS > 10) begin : neuron_10
            neuron #(
                .NEURON_WIDTH(NUM_FEATURES),
                .DATA_BITS   (DATA_BITS),
                .WEIGHT_BITS (WEIGHT_BITS),
                .BIAS_BITS   (BIAS_BITS),
                .WeightFile  ("edge_encoder_w_2_10.mif"),
                .BiasFile    ("edge_encoder_b_2_10.mif")
            ) inst (
                .clk                (clk),
                .rstn               (rstn),
                .activation_function(activation_function),
                .data_in_flat       (data_in_flat),
                .counter            (counter),
                .data_out           (neuron_outputs[10])
            );
        end

        if (NUM_NEURONS > 11) begin : neuron_11
            neuron #(
                .NEURON_WIDTH(NUM_FEATURES),
                .DATA_BITS   (DATA_BITS),
                .WEIGHT_BITS (WEIGHT_BITS),
                .BIAS_BITS   (BIAS_BITS),
                .WeightFile  ("edge_encoder_w_2_11.mif"),
                .BiasFile    ("edge_encoder_b_2_11.mif")
            ) inst (
                .clk                (clk),
                .rstn               (rstn),
                .activation_function(activation_function),
                .data_in_flat       (data_in_flat),
                .counter            (counter),
                .data_out           (neuron_outputs[11])
            );
        end

        if (NUM_NEURONS > 12) begin : neuron_12
            neuron #(
                .NEURON_WIDTH(NUM_FEATURES),
                .DATA_BITS   (DATA_BITS),
                .WEIGHT_BITS (WEIGHT_BITS),
                .BIAS_BITS   (BIAS_BITS),
                .WeightFile  ("edge_encoder_w_2_12.mif"),
                .BiasFile    ("edge_encoder_b_2_12.mif")
            ) inst (
                .clk                (clk),
                .rstn               (rstn),
                .activation_function(activation_function),
                .data_in_flat       (data_in_flat),
                .counter            (counter),
                .data_out           (neuron_outputs[12])
            );
        end

        if (NUM_NEURONS > 13) begin : neuron_13
            neuron #(
                .NEURON_WIDTH(NUM_FEATURES),
                .DATA_BITS   (DATA_BITS),
                .WEIGHT_BITS (WEIGHT_BITS),
                .BIAS_BITS   (BIAS_BITS),
                .WeightFile  ("edge_encoder_w_2_13.mif"),
                .BiasFile    ("edge_encoder_b_2_13.mif")
            ) inst (
                .clk                (clk),
                .rstn               (rstn),
                .activation_function(activation_function),
                .data_in_flat       (data_in_flat),
                .counter            (counter),
                .data_out           (neuron_outputs[13])
            );
        end

        if (NUM_NEURONS > 14) begin : neuron_14
            neuron #(
                .NEURON_WIDTH(NUM_FEATURES),
                .DATA_BITS   (DATA_BITS),
                .WEIGHT_BITS (WEIGHT_BITS),
                .BIAS_BITS   (BIAS_BITS),
                .WeightFile  ("edge_encoder_w_2_14.mif"),
                .BiasFile    ("edge_encoder_b_2_14.mif")
            ) inst (
                .clk                (clk),
                .rstn               (rstn),
                .activation_function(activation_function),
                .data_in_flat       (data_in_flat),
                .counter            (counter),
                .data_out           (neuron_outputs[14])
            );
        end

        if (NUM_NEURONS > 15) begin : neuron_15
            neuron #(
                .NEURON_WIDTH(NUM_FEATURES),
                .DATA_BITS   (DATA_BITS),
                .WEIGHT_BITS (WEIGHT_BITS),
                .BIAS_BITS   (BIAS_BITS),
                .WeightFile  ("edge_encoder_w_2_15.mif"),
                .BiasFile    ("edge_encoder_b_2_15.mif")
            ) inst (
                .clk                (clk),
                .rstn               (rstn),
                .activation_function(activation_function),
                .data_in_flat       (data_in_flat),
                .counter            (counter),
                .data_out           (neuron_outputs[15])
            );
        end

        if (NUM_NEURONS > 16) begin : neuron_16
            neuron #(
                .NEURON_WIDTH(NUM_FEATURES),
                .DATA_BITS   (DATA_BITS),
                .WEIGHT_BITS (WEIGHT_BITS),
                .BIAS_BITS   (BIAS_BITS),
                .WeightFile  ("edge_encoder_w_2_16.mif"),
                .BiasFile    ("edge_encoder_b_2_16.mif")
            ) inst (
                .clk                (clk),
                .rstn               (rstn),
                .activation_function(activation_function),
                .data_in_flat       (data_in_flat),
                .counter            (counter),
                .data_out           (neuron_outputs[16])
            );
        end

        if (NUM_NEURONS > 17) begin : neuron_17
            neuron #(
                .NEURON_WIDTH(NUM_FEATURES),
                .DATA_BITS   (DATA_BITS),
                .WEIGHT_BITS (WEIGHT_BITS),
                .BIAS_BITS   (BIAS_BITS),
                .WeightFile  ("edge_encoder_w_2_17.mif"),
                .BiasFile    ("edge_encoder_b_2_17.mif")
            ) inst (
                .clk                (clk),
                .rstn               (rstn),
                .activation_function(activation_function),
                .data_in_flat       (data_in_flat),
                .counter            (counter),
                .data_out           (neuron_outputs[17])
            );
        end

        if (NUM_NEURONS > 18) begin : neuron_18
            neuron #(
                .NEURON_WIDTH(NUM_FEATURES),
                .DATA_BITS   (DATA_BITS),
                .WEIGHT_BITS (WEIGHT_BITS),
                .BIAS_BITS   (BIAS_BITS),
                .WeightFile  ("edge_encoder_w_2_18.mif"),
                .BiasFile    ("edge_encoder_b_2_18.mif")
            ) inst (
                .clk                (clk),
                .rstn               (rstn),
                .activation_function(activation_function),
                .data_in_flat       (data_in_flat),
                .counter            (counter),
                .data_out           (neuron_outputs[18])
            );
        end

        if (NUM_NEURONS > 19) begin : neuron_19
            neuron #(
                .NEURON_WIDTH(NUM_FEATURES),
                .DATA_BITS   (DATA_BITS),
                .WEIGHT_BITS (WEIGHT_BITS),
                .BIAS_BITS   (BIAS_BITS),
                .WeightFile  ("edge_encoder_w_2_19.mif"),
                .BiasFile    ("edge_encoder_b_2_19.mif")
            ) inst (
                .clk                (clk),
                .rstn               (rstn),
                .activation_function(activation_function),
                .data_in_flat       (data_in_flat),
                .counter            (counter),
                .data_out           (neuron_outputs[19])
            );
        end

        if (NUM_NEURONS > 20) begin : neuron_20
            neuron #(
                .NEURON_WIDTH(NUM_FEATURES),
                .DATA_BITS   (DATA_BITS),
                .WEIGHT_BITS (WEIGHT_BITS),
                .BIAS_BITS   (BIAS_BITS),
                .WeightFile  ("edge_encoder_w_2_20.mif"),
                .BiasFile    ("edge_encoder_b_2_20.mif")
            ) inst (
                .clk                (clk),
                .rstn               (rstn),
                .activation_function(activation_function),
                .data_in_flat       (data_in_flat),
                .counter            (counter),
                .data_out           (neuron_outputs[20])
            );
        end

        if (NUM_NEURONS > 21) begin : neuron_21
            neuron #(
                .NEURON_WIDTH(NUM_FEATURES),
                .DATA_BITS   (DATA_BITS),
                .WEIGHT_BITS (WEIGHT_BITS),
                .BIAS_BITS   (BIAS_BITS),
                .WeightFile  ("edge_encoder_w_2_21.mif"),
                .BiasFile    ("edge_encoder_b_2_21.mif")
            ) inst (
                .clk                (clk),
                .rstn               (rstn),
                .activation_function(activation_function),
                .data_in_flat       (data_in_flat),
                .counter            (counter),
                .data_out           (neuron_outputs[21])
            );
        end

        if (NUM_NEURONS > 22) begin : neuron_22
            neuron #(
                .NEURON_WIDTH(NUM_FEATURES),
                .DATA_BITS   (DATA_BITS),
                .WEIGHT_BITS (WEIGHT_BITS),
                .BIAS_BITS   (BIAS_BITS),
                .WeightFile  ("edge_encoder_w_2_22.mif"),
                .BiasFile    ("edge_encoder_b_2_22.mif")
            ) inst (
                .clk                (clk),
                .rstn               (rstn),
                .activation_function(activation_function),
                .data_in_flat       (data_in_flat),
                .counter            (counter),
                .data_out           (neuron_outputs[22])
            );
        end

        if (NUM_NEURONS > 23) begin : neuron_23
            neuron #(
                .NEURON_WIDTH(NUM_FEATURES),
                .DATA_BITS   (DATA_BITS),
                .WEIGHT_BITS (WEIGHT_BITS),
                .BIAS_BITS   (BIAS_BITS),
                .WeightFile  ("edge_encoder_w_2_23.mif"),
                .BiasFile    ("edge_encoder_b_2_23.mif")
            ) inst (
                .clk                (clk),
                .rstn               (rstn),
                .activation_function(activation_function),
                .data_in_flat       (data_in_flat),
                .counter            (counter),
                .data_out           (neuron_outputs[23])
            );
        end

        if (NUM_NEURONS > 24) begin : neuron_24
            neuron #(
                .NEURON_WIDTH(NUM_FEATURES),
                .DATA_BITS   (DATA_BITS),
                .WEIGHT_BITS (WEIGHT_BITS),
                .BIAS_BITS   (BIAS_BITS),
                .WeightFile  ("edge_encoder_w_2_24.mif"),
                .BiasFile    ("edge_encoder_b_2_24.mif")
            ) inst (
                .clk                (clk),
                .rstn               (rstn),
                .activation_function(activation_function),
                .data_in_flat       (data_in_flat),
                .counter            (counter),
                .data_out           (neuron_outputs[24])
            );
        end

        if (NUM_NEURONS > 25) begin : neuron_25
            neuron #(
                .NEURON_WIDTH(NUM_FEATURES),
                .DATA_BITS   (DATA_BITS),
                .WEIGHT_BITS (WEIGHT_BITS),
                .BIAS_BITS   (BIAS_BITS),
                .WeightFile  ("edge_encoder_w_2_25.mif"),
                .BiasFile    ("edge_encoder_b_2_25.mif")
            ) inst (
                .clk                (clk),
                .rstn               (rstn),
                .activation_function(activation_function),
                .data_in_flat       (data_in_flat),
                .counter            (counter),
                .data_out           (neuron_outputs[25])
            );
        end

        if (NUM_NEURONS > 26) begin : neuron_26
            neuron #(
                .NEURON_WIDTH(NUM_FEATURES),
                .DATA_BITS   (DATA_BITS),
                .WEIGHT_BITS (WEIGHT_BITS),
                .BIAS_BITS   (BIAS_BITS),
                .WeightFile  ("edge_encoder_w_2_26.mif"),
                .BiasFile    ("edge_encoder_b_2_26.mif")
            ) inst (
                .clk                (clk),
                .rstn               (rstn),
                .activation_function(activation_function),
                .data_in_flat       (data_in_flat),
                .counter            (counter),
                .data_out           (neuron_outputs[26])
            );
        end

        if (NUM_NEURONS > 27) begin : neuron_27
            neuron #(
                .NEURON_WIDTH(NUM_FEATURES),
                .DATA_BITS   (DATA_BITS),
                .WEIGHT_BITS (WEIGHT_BITS),
                .BIAS_BITS   (BIAS_BITS),
                .WeightFile  ("edge_encoder_w_2_27.mif"),
                .BiasFile    ("edge_encoder_b_2_27.mif")
            ) inst (
                .clk                (clk),
                .rstn               (rstn),
                .activation_function(activation_function),
                .data_in_flat       (data_in_flat),
                .counter            (counter),
                .data_out           (neuron_outputs[27])
            );
        end

        if (NUM_NEURONS > 28) begin : neuron_28
            neuron #(
                .NEURON_WIDTH(NUM_FEATURES),
                .DATA_BITS   (DATA_BITS),
                .WEIGHT_BITS (WEIGHT_BITS),
                .BIAS_BITS   (BIAS_BITS),
                .WeightFile  ("edge_encoder_w_2_28.mif"),
                .BiasFile    ("edge_encoder_b_2_28.mif")
            ) inst (
                .clk                (clk),
                .rstn               (rstn),
                .activation_function(activation_function),
                .data_in_flat       (data_in_flat),
                .counter            (counter),
                .data_out           (neuron_outputs[28])
            );
        end

        if (NUM_NEURONS > 29) begin : neuron_29
            neuron #(
                .NEURON_WIDTH(NUM_FEATURES),
                .DATA_BITS   (DATA_BITS),
                .WEIGHT_BITS (WEIGHT_BITS),
                .BIAS_BITS   (BIAS_BITS),
                .WeightFile  ("edge_encoder_w_2_29.mif"),
                .BiasFile    ("edge_encoder_b_2_29.mif")
            ) inst (
                .clk                (clk),
                .rstn               (rstn),
                .activation_function(activation_function),
                .data_in_flat       (data_in_flat),
                .counter            (counter),
                .data_out           (neuron_outputs[29])
            );
        end

        if (NUM_NEURONS > 30) begin : neuron_30
            neuron #(
                .NEURON_WIDTH(NUM_FEATURES),
                .DATA_BITS   (DATA_BITS),
                .WEIGHT_BITS (WEIGHT_BITS),
                .BIAS_BITS   (BIAS_BITS),
                .WeightFile  ("edge_encoder_w_2_30.mif"),
                .BiasFile    ("edge_encoder_b_2_30.mif")
            ) inst (
                .clk                (clk),
                .rstn               (rstn),
                .activation_function(activation_function),
                .data_in_flat       (data_in_flat),
                .counter            (counter),
                .data_out           (neuron_outputs[30])
            );
        end

        if (NUM_NEURONS > 31) begin : neuron_31
            neuron #(
                .NEURON_WIDTH(NUM_FEATURES),
                .DATA_BITS   (DATA_BITS),
                .WEIGHT_BITS (WEIGHT_BITS),
                .BIAS_BITS   (BIAS_BITS),
                .WeightFile  ("edge_encoder_w_2_31.mif"),
                .BiasFile    ("edge_encoder_b_2_31.mif")
            ) inst (
                .clk                (clk),
                .rstn               (rstn),
                .activation_function(activation_function),
                .data_in_flat       (data_in_flat),
                .counter            (counter),
                .data_out           (neuron_outputs[31])
            );
        end
    endgenerate

endmodule
