#!/usr/bin/env python3
"""
gen_encoder_layers.py
Generates edge_encoder_layer_{1,2,3}.v and node_encoder_layer_{1,2,3}.v.

Initial scaffolding: emits a single placeholder layer template so the
encoder top module has something to instantiate. Real weights are loaded
from mif/ at simulation time.
"""

import os
import argparse

LAYERS = [
    ("edge", 1, 6),
    ("edge", 2, 32),
    ("edge", 3, 32),
    ("node", 1, 12),
    ("node", 2, 32),
    ("node", 3, 32),
]
NUM_NEURONS = 32
DATA_BITS = 8
WEIGHT_BITS = 8


def emit_layer(net, layer, in_features, outdir):
    fname = os.path.join(outdir, f"{net}_encoder_layer_{layer}.v")
    with open(fname, "w") as f:
        f.write(f"// Auto-generated by gen_encoder_layers.py\n")
        f.write(f"// {net} encoder layer {layer}: {in_features} -> {NUM_NEURONS}\n")
        f.write(f"module {net}_encoder_layer_{layer} ();\n")
        f.write("endmodule\n")
    return fname


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--outdir", default=".")
    args = ap.parse_args()
    for cfg in LAYERS:
        emit_layer(*cfg, args.outdir)


if __name__ == "__main__":
    main()
