#!/usr/bin/env python3
"""
gen_encoder_layers.py
Generates edge_encoder_layer_{1,2,3}.v and node_encoder_layer_{1,2,3}.v

Layer configs:
  edge L1: 6  input features  -> 32 neurons
  edge L2: 32 input features  -> 32 neurons
  edge L3: 32 input features  -> 32 neurons
  node L1: 12 input features  -> 32 neurons
  node L2: 32 input features  -> 32 neurons
  node L3: 32 input features  -> 32 neurons

Usage:
    python gen_encoder_layers.py [--outdir ./]
"""

import os, argparse

# -----------------------------------------------------------------------
# Layer configurations
# -----------------------------------------------------------------------
LAYERS = [
    # (net,    layer, in_features)
    ("edge",   1,     6),
    ("edge",   2,     32),
    ("edge",   3,     32),
    ("node",   1,     12),
    ("node",   2,     32),
    ("node",   3,     32),
]

NUM_NEURONS  = 32
DATA_BITS    = 8
WEIGHT_BITS  = 8
BIAS_BITS    = 8
DONE_DELAY   = 2   # cycles to wait after counter_done before asserting done_reg

LN = dict(
    data_bits      = 24,
    data_frac_bits = 10,
    scale_bits     = 8,
    frac_bits      = 6,
    inv_sqrt_bits  = 16,
    inv_sqrt_frac  = 11,
    var_bits       = 45,
    lut_bits       = 5,
    lut_size       = 20,
    epsilon        = 1,
    out_bits       = 8,
    out_frac_bits  = 4,
)

# -----------------------------------------------------------------------
# Neuron instance block
# -----------------------------------------------------------------------
def neuron_instances(net, layer, num_features, num_neurons):
    lines = []
    for n in range(num_neurons):
        wf = f"{net}_encoder_w_{layer}_{n}.mif"
        bf = f"{net}_encoder_b_{layer}_{n}.mif"
        lines.append(f"""
        if (NUM_NEURONS > {n}) begin : neuron_{n}
            neuron #(
                .NEURON_WIDTH(NUM_FEATURES),
                .DATA_BITS   (DATA_BITS),
                .WEIGHT_BITS (WEIGHT_BITS),
                .BIAS_BITS   (BIAS_BITS),
                .WeightFile  ("{wf}"),
                .BiasFile    ("{bf}")
            ) inst (
                .clk                (clk),
                .rstn               (rstn),
                .activation_function(activation_function),
                .data_in_flat       (data_in_flat),
                .counter            (counter),
                .data_out           (neuron_outputs[{n}])
            );
        end""")
    return "\n".join(lines)

# -----------------------------------------------------------------------
# Full module
# -----------------------------------------------------------------------
def gen_module(net, layer, num_features):
    module_name = f"{net}_encoder_layer_{layer}"
    gamma_file  = f"ln_gamma_{layer}.mif"
    delay_bits  = max(2, DONE_DELAY.bit_length() + 1) if DONE_DELAY > 0 else 2
    neuron_out_bits = DATA_BITS + WEIGHT_BITS + 8

    neurons = neuron_instances(net, layer, num_features, NUM_NEURONS)

    return f"""`timescale 1ns / 1ps
//==============================================================================
// {module_name}.v  --  Auto-generated by gen_encoder_layers.py
//
// Layer {layer}: {num_features} inputs -> {NUM_NEURONS} neurons -> rms norm -> {NUM_NEURONS} x {LN['out_bits']}-bit Q4.4 outputs
//==============================================================================
module {module_name} #(
    parameter LAYER_NO        = {layer},
    parameter NUM_NEURONS     = {NUM_NEURONS},
    parameter NUM_FEATURES    = {num_features},
    parameter DATA_BITS       = {DATA_BITS},
    parameter WEIGHT_BITS     = {WEIGHT_BITS},
    parameter BIAS_BITS       = {BIAS_BITS},
    // RMS norm
    parameter LN_DATA_BITS      = {LN['data_bits']},
    parameter LN_DATA_FRAC_BITS = {LN['data_frac_bits']},
    parameter LN_SCALE_BITS     = {LN['scale_bits']},
    parameter LN_FRAC_BITS      = {LN['frac_bits']},
    parameter LN_INV_SQRT_BITS  = {LN['inv_sqrt_bits']},
    parameter LN_INV_SQRT_FRAC  = {LN['inv_sqrt_frac']},
    parameter LN_VAR_BITS       = {LN['var_bits']},
    parameter LN_LUT_BITS       = {LN['lut_bits']},
    parameter LN_LUT_SIZE       = {LN['lut_size']},
    parameter LN_EPSILON        = {LN['epsilon']},
    parameter LN_OUT_BITS       = {LN['out_bits']},
    parameter LN_OUT_FRAC_BITS  = {LN['out_frac_bits']},
    parameter USE_RMS_NORM    = 1,
    parameter GammaFile         = "{gamma_file}"
)(
    input  clk,
    input  rstn,                                                    // used as layer_held by parent
    input  activation_function,
    input  signed [NUM_FEATURES*DATA_BITS-1:0]   data_in_flat,

    output signed [NUM_NEURONS*LN_OUT_BITS-1:0]  data_out_flat,
    output valid_out,
    output done
);

    localparam NEURON_OUT_BITS = DATA_BITS + WEIGHT_BITS + 8;

    //--------------------------------------------------------------------------
    // Counter: .rstn(rstn) — parent drives rstn=layer_held, so counter runs
    // only while the layer is active.
    //--------------------------------------------------------------------------
    wire [31:0] counter;
    wire        counter_done;

    counter #(
        .END_COUNTER((NUM_FEATURES + 3) / 4)   // ceiling division — covers all features
    ) layer_counter (
        .clk               (clk),
        .rstn              (rstn),
        .counter_out       (counter),
        .counter_donestatus(counter_done)
    );

    //--------------------------------------------------------------------------
    // Computation active + done state machine.
    // done is a 1-cycle pulse after counter_done + done_delay cycles.
    // The parent (edge_encoder / node_encoder) reads valid_out (= rms_norm
    // done) as layer_done, not this done port — done() is tied open there.
    // The state machine is kept for completeness and future use.
    //--------------------------------------------------------------------------
    reg computation_active;
    reg done_reg;
    reg [{delay_bits-1}:0] done_delay_counter;

    always @(posedge clk or negedge rstn) begin
        if (!rstn) begin
            computation_active <= 0;
            done_reg           <= 0;
            done_delay_counter <= 0;
        end else begin
            if (!computation_active && !done_reg) begin
                computation_active <= 1;
                done_delay_counter <= 0;
            end else if (counter_done && computation_active && !done_reg) begin
                if (done_delay_counter < {DONE_DELAY}) begin
                    done_delay_counter <= done_delay_counter + 1;
                end else begin
                    done_reg           <= 1;
                    computation_active <= 0;
                    done_delay_counter <= 0;
                end
            end else if (done_reg) begin
                // Hold done until the parent drops layer_held after valid_out.
                computation_active <= 0;
            end
        end
    end

    assign done = done_reg;

    //--------------------------------------------------------------------------
    // Raw neuron outputs
    //--------------------------------------------------------------------------
    wire signed [NEURON_OUT_BITS-1:0] neuron_outputs [0:NUM_NEURONS-1];

    //--------------------------------------------------------------------------
    // Gamma — load from MIF, pack via generate/assign
    //--------------------------------------------------------------------------
    reg signed [LN_SCALE_BITS-1:0] gamma_arr [0:NUM_NEURONS-1];

    initial begin
        $readmemb(GammaFile, gamma_arr);
    end

    wire signed [NUM_NEURONS*LN_SCALE_BITS-1:0] ln_gamma;

    genvar gi;
    generate
        for (gi = 0; gi < NUM_NEURONS; gi = gi + 1) begin : ln_param_pack
            assign ln_gamma[gi*LN_SCALE_BITS +: LN_SCALE_BITS] = gamma_arr[gi];
        end
    endgenerate

    //--------------------------------------------------------------------------
    // ln_start: 1-cycle pulse on done_reg rising edge
    //--------------------------------------------------------------------------
    reg done_reg_r;
    reg ln_start;

    always @(posedge clk or negedge rstn) begin
        if (!rstn) begin
            done_reg_r <= 1'b0;
            ln_start   <= 1'b0;
        end else begin
            done_reg_r <= done_reg;
            ln_start   <= done_reg & ~done_reg_r;
        end
    end

    //--------------------------------------------------------------------------
    // Latch + sign-extend neuron outputs into ln_data_in on ln_start pulse
    //--------------------------------------------------------------------------
    reg signed [NUM_NEURONS*LN_DATA_BITS-1:0] ln_data_in;

    integer n;
    always @(posedge clk or negedge rstn) begin
        if (!rstn) begin
            ln_data_in <= {{(NUM_NEURONS*LN_DATA_BITS){{1'b0}}}};
        end else if (done_reg & ~done_reg_r) begin
            for (n = 0; n < NUM_NEURONS; n = n + 1) begin
                ln_data_in[n*LN_DATA_BITS +: LN_DATA_BITS] <=
                    {{{{(LN_DATA_BITS-NEURON_OUT_BITS){{neuron_outputs[n][NEURON_OUT_BITS-1]}}}},
                      neuron_outputs[n]}};
            end
        end
    end

    //--------------------------------------------------------------------------
    // RMS norm / bypass
    //--------------------------------------------------------------------------
    generate
        if (USE_RMS_NORM) begin : gen_rms_norm
            rms_norm #(
                .NUM_FEATURES      (NUM_NEURONS),
                .DATA_BITS         (LN_DATA_BITS),
                .DATA_FRAC_BITS    (LN_DATA_FRAC_BITS),
                .SCALE_BITS        (LN_SCALE_BITS),
                .FRAC_BITS         (LN_FRAC_BITS),
                .INV_SQRT_BITS     (LN_INV_SQRT_BITS),
                .INV_SQRT_FRAC_BITS(LN_INV_SQRT_FRAC),
                .VAR_BITS          (LN_VAR_BITS),
                .LUT_BITS          (LN_LUT_BITS),
                .LUT_SIZE          (LN_LUT_SIZE),
                .EPSILON           (LN_EPSILON),
                .OUT_BITS          (LN_OUT_BITS),
                .OUT_FRAC_BITS     (LN_OUT_FRAC_BITS)
            ) u_rms_norm (
                .clk      (clk),
                .rstn     (rstn),
                .valid_in (ln_start),
                .act_en   (activation_function),
                .data_in  (ln_data_in),
                .gamma    (ln_gamma),
                .valid_out(valid_out),
                .busy     (),
                .data_out (data_out_flat)
            );
        end else begin : gen_bypass_rms_norm
            layer_norm_relu #(
                .NUM_FEATURES      (NUM_NEURONS),
                .DATA_BITS         (LN_DATA_BITS),
                .DATA_FRAC_BITS    (LN_DATA_FRAC_BITS),
                .OUT_BITS          (LN_OUT_BITS),
                .OUT_FRAC_BITS     (LN_OUT_FRAC_BITS)
            ) u_rms_norm_bypass (
                .clk      (clk),
                .rstn     (rstn),
                .valid_in (ln_start),
                .act_en   (activation_function),
                .data_in  (ln_data_in),
                .valid_out(valid_out),
                .data_out (data_out_flat)
            );
        end
    endgenerate

    //--------------------------------------------------------------------------
    // Neuron instances
    //--------------------------------------------------------------------------
    generate
{neurons}
    endgenerate

endmodule
"""

# -----------------------------------------------------------------------
# Main
# -----------------------------------------------------------------------
def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--outdir", default="./", help="Output directory")
    args = parser.parse_args()
    os.makedirs(args.outdir, exist_ok=True)

    for net, layer, num_features in LAYERS:
        module_name = f"{net}_encoder_layer_{layer}"
        filename    = os.path.join(args.outdir, f"{module_name}.v")
        verilog     = gen_module(net, layer, num_features)
        with open(filename, "w", encoding="utf-8") as f:
            f.write(verilog)
        print(f"Written: {filename}  ({num_features} features -> {NUM_NEURONS} neurons)")

    print(f"\nDone. {len(LAYERS)} file(s) written to '{args.outdir}/'")

if __name__ == "__main__":
    main()
